# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KpjFXY6vchdxObe-x8ULcbn4MBZVLeUJ
"""

#calulator(assignment3)
ifcontinue=1
while(ifcontinue==1):

 p=int(input("enter first number"))
 q=int(input("enter second number"))
 op=input("Choose an operator \n1.'+'\n2.'-'\n3.'*'\n4.'/' ")
 
 if op=="+":
      c=p+q
 elif op== "-":
      c=p-q
 elif op=="*":
      c=p*q;
 elif op== "/":
      c=p/q;
 else:
       print("default") 
 print("The answer is")       
 with open("ans.txt","w") as f:
   f.write(str(c))
 with open("ans.txt","r") as f:
   print(f.read())
   
 ifcontinue=int(input("if want to continue then press 1 otherwise 0:"))